version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8001"]
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data:
